# CamStories language modeling config - Real story data

defaults:
  - arch: hrm_v1
  - _self_

# Disable wandb logging
project_name: null
run_name: null

hydra:
  output_subdir: null

# Data path - our CamStories dataset
data_path: dataset/camstories_test

# Hyperparams - Training
global_batch_size: 16  # Smaller batch for longer sequences
epochs: 6  # Fewer epochs for larger dataset
eval_interval: 2
checkpoint_every_eval: True

lr: 5e-5  # Lower learning rate for story data
lr_min_ratio: 1.0
lr_warmup_steps: 50

# Standard hyperparameter settings for LM
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 1e-2