# RoBERTa language modeling test config

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data path - our RoBERTa dataset
data_path: dataset/roberta_test

# Hyperparams - Training (reduced for quick test)
global_batch_size: 32  # Much smaller than original 768

epochs: 10  # Very small for quick test
eval_interval: 5
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 10  # Much smaller than original 2000

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 1e-2